colorscheme wombat
if has("mac")
  set guifont=Monaco:h18.00
else
  set gfn=DejaVu\ Sans\ Mono\ Bold\ 18
end

set guioptions-=T  "remove toolbar
set guioptions-=m  "remove menu

set lines=47
set columns=161
